# Immutable constants & default keys for agent-arena

# Versioning
EXPECTED_CONFIG_VERSION = "1.00"
PROTOCOL_VERSION = "1.00"

# Roles
ROLE_PLAYER_1 = "PLAYER_1"
ROLE_PLAYER_2 = "PLAYER_2"
ROLES = [ROLE_PLAYER_1, ROLE_PLAYER_2]

# Message type constants
MSG_REGISTER = "REGISTER"
MSG_REGISTER_ACK = "REGISTER_ACK"
MSG_ROLE_ASSIGN = "ROLE_ASSIGN"
MSG_GAME_START = "GAME_START"
MSG_MOVE_REQUEST = "MOVE_REQUEST"
MSG_MOVE_SUBMIT = "MOVE_SUBMIT"
MSG_STATE_UPDATE = "STATE_UPDATE"
MSG_GAME_OVER = "GAME_OVER"
MSG_ERROR = "ERROR"
MSG_HEARTBEAT = "HEARTBEAT"

# Network Defaults (used if config fails or fallback required)
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 9000
DEFAULT_MAX_FRAME_SIZE = 10 * 1024 * 1024  # 10MB
